```java
import java.util.Arrays;

public class ShortestPath {
    // A class to represent a weighted edge in graph
    class Edge {
        int src, dest, weight;
        
        // Constructor
        Edge(int src, int dest, int weight) {
            this.src = src;
            this.dest = dest;
            this.weight = weight;
        }
    }
    
    // Function to run BellmanFord Algorithm
    public int[] bellmanFord(Edge[] edges, int numOfVertices, int sourceVertex) {
        int[] dist = new int[numOfVertices];
        Arrays.fill(dist, Integer.MAX_VALUE);
        dist[sourceVertex] = 0;

        // Relax edges |V| - 1 times to get shortest path to all vertices
        for (int i = 0; i < numOfVertices - 1; i++) {
            for (Edge edge : edges) {
                int u = edge.src;
                int v = edge.dest;
                int weight = edge.weight;
                if (dist[u] != Integer.MAX_VALUE && dist[u] + weight < dist[v]) {
                    dist[v] = dist[u] + weight;
                }
            }
        }

        // Detect negative cycles
        for (Edge edge : edges) {
            int u = edge.src;
            int v = edge.dest;
            int weight = edge.weight;
            if (dist[u] != Integer.MAX_VALUE && dist[u] + weight < dist[v]) {
                throw new IllegalArgumentException("Graph contains a negative-weight cycle");
            }
        }

        return dist;
    }
}
```
// generated by TicketToPR at 2025-11-14 17:25:07
