```java
import java.util.Arrays;

public class Main {
  // a class to represent a weighted edge in graph
  class Edge {
    int src, dest, weight;
    Edge() {
      src = dest = weight = 0;
    }
  };

  int V, E;
  Edge edge[];

  Main(int v, int e) {
    V = v;
    E = e;
    edge = new Edge[e];
    for (int i = 0; i < e; ++i)
      edge[i] = new Edge();
  }

  // function implementing BellmanFord algorithm
  void bellmanFordAlgorithm1(Main graph, int src) {
    int V = graph.V, E = graph.E;
    int dist[] = new int[V];
    // Initialize distances from src to all other vertices as INFINITE
    for (int i = 0; i < V; ++i)
      dist[i] = Integer.MAX_VALUE;
    dist[src] = 0;

    // Relax all edges |V| - 1 times. A simple shortest path from src to any other
    // vertex can have at-most |V| - 1 edges
    for (int i = 1; i < V; ++i) {
      for (int j = 0; j < E; ++j) {
        int u = graph.edge[j].src;
        int v = graph.edge[j].dest;
        int weight = graph.edge[j].weight;
        if (dist[u] != Integer.MAX_VALUE && dist[u] + weight < dist[v])
          dist[v] = dist[u] + weight;
      }
    }

    // Check for negative-weight cycles. 
    // If we get a shorter path, then there is a cycle.
    for (int j = 0; j < E; ++j) {
      int u = graph.edge[j].src;
      int v = graph.edge[j].dest;
      int weight = graph.edge[j].weight;
      if (dist[u] != Integer.MAX_VALUE && dist[u] + weight < dist[v]) {
        System.out.println("Graph contains negative weight cycle");
        return;
      }
    }
    printArr(dist, V);
  }

  // utility function to print distances array containing shortest distance from source
  void printArr(int dist[], int V) {
    System.out.println("Vertex   Distance from Source");
    for (int i = 0; i < V; ++i)
      System.out.println(i + "\t\t" + dist[i]);
  }

  // main function to test above functions
  public static void main(String[] args) {
    int V = 5; // Number of vertices
    int E = 8; // Number of edges

    Main graph = new Main(V, E);

    // add your edges with source, destination and weight
    // example: 
    // graph.edge[0].src = 0;
    // graph.edge[0].dest = 1;
    // graph.edge[0].weight = -1;

    graph.bellmanFordAlgorithm1(graph, 0);
  }
}
```
// generated by TicketToPR at 2025-11-14 17:30:58
