```python
# Defining the Bellman-Ford algorithm
def BellmanFord(graph, V, E, src):
    # Initializing distance from source to all other vertices as INFINITE
    dis = [float("Inf")] * V
    dis[src] = 0
 
    # Relax all edges |V| - 1 times
    for i in range(V - 1):
        for j in range(E):
            if dis[graph[j][0]] + graph[j][2] < dis[graph[j][1]]:
                dis[graph[j][1]] = dis[graph[j][0]] + graph[j][2]
 
    # Checking for negative-weight cycles
    for i in range(E):
        x = graph[i][0]
        y = graph[i][1]
        weight = graph[i][2]
        if dis[x] != float("Inf") and dis[x] + weight < dis[y]:
            print("Graph contains negative weight cycle")

    return dis
```
# generated by TicketToPR at 2025-11-14 17:32:19
