```java
public class Main {

    public static void main(String[] args) {
        int number1 = 10; 
        int number2 = 2; 
        // Doubles are used to not lose precision while dividing
        double result = divideNumbers((double) number1, (double) number2);
        System.out.println("The result is " + result);
    }

    /**
     * This method is used to divide two numbers.
     * @param number1 This is the dividend
     * @param number2 This is the divisor
     * @return double This returns the result of division of number1 by number2.
     */
    public static double divideNumbers(double number1, double number2) {
        if (number2 == 0) {
            throw new ArithmeticException("Cannot divide by zero"); 
        } else {
            return number1 / number2;
        }
    }
}
```
// generated by TicketToPR at 2025-11-15 18:51:30
