```java
public class Main {

    public static void main(String[] args) {
        double num1 = 10.0;
        double num2 = 2.0;
        
        // Validate denominator; it should not be zero
        if (num2 != 0) {
            double result = divideNumbers(num1, num2);
            System.out.println("Result: " + result);
        } else {
            System.out.println("Invalid input. Division by zero is not allowed.");
        }
    }
    
    /**
     * Method to divide two numbers.
     * 
     * @param num1 The first number - numerator.
     * @param num2 The second number - denominator.
     * @return The result of division.
     */
    public static double divideNumbers(double num1, double num2) {
        return num1 / num2;
    }
}
```
// generated by TicketToPR at 2025-11-15 18:50:01
