```java
public class Main {

    public static void main(String[] args) {
        double num1 = 10.0;
        double num2 = 2.0;
        double result = divideTwoNumbers(num1, num2);
        System.out.println(result);
    }

    /**
     * This method divides two numbers
     * 
     * @param num1 The first number
     * @param num2 The second number
     * @return The result of the division
     */
    public static double divideTwoNumbers(double num1, double num2) {
        // Check if the denominator is 0 to avoid division by zero error
        if (num2 == 0) {
            throw new IllegalArgumentException("Denominator cannot be zero");
        }
        return num1 / num2;
    }
}
```
// generated by TicketToPR at 2025-11-15 18:49:08
