```java
// This is a simple Java class to add two numbers
public class AddNumbers {
    
    // Method to add two numbers
    public int addTwoNumbers(int num1, int num2) {
        
        // Variable to store the sum of two numbers
        int sum;
        
        // Adding two numbers
        sum = num1 + num2;
        
        // Returning the sum
        return sum;
     }
}
```
// generated by TicketToPR at 2025-11-14 16:45:33
