```java
import java.util.Comparator;
import java.util.PriorityQueue;
import java.util.Scanner;

class Edge {
    int src, dest, weight;

    public Edge(int src, int dest, int weight) {
        this.src = src;
        this.dest = dest;
        this.weight = weight;
    }
}

class Subset {
    int parent, rank;

    public Subset(int parent, int rank) {
        this.parent = parent;
        this.rank = rank;
    }
}

public class KruskalAlgorithm {

    int vertices, edges;
    Edge edge[];

    private int find(Subset subsets[], int i) {
        if(subsets[i].parent != i) {
            subsets[i].parent = find(subsets, subsets[i].parent);
        }
        return subsets[i].parent;
    }

    private void union(Subset subsets[], int x, int y) {
        int xroot = find(subsets, x);
        int yroot = find(subsets, y);

        if(subsets[xroot].rank < subsets[yroot].rank) {
            subsets[xroot].parent = yroot;
        } else if(subsets[xroot].rank > subsets[yroot].rank) {
            subsets[yroot].parent = xroot;
        } else {
            subsets[yroot].parent = xroot;
            subsets[xroot].rank++;
        }
    }

    void KruskalAlgo() {
        Edge result[] = new Edge[vertices];
        int e = 0;
        int i = 0;
        for(i = 0; i < vertices; ++i) {
            result[i] = new Edge(0, 0, 0);
        }

        PriorityQueue<Edge> pq = new PriorityQueue<>(edges, new Comparator<Edge>() {
            @Override
            public int compare(Edge o1, Edge o2) {
                return o1.weight - o2.weight;
            }
        });

        for(i = 0; i < edges; ++i) {
            pq.add(edge[i]);
        }

        Subset subsets[] = new Subset[vertices];
        for(i = 0; i < vertices; ++i) {
            subsets[i] = new Subset(i, 0);
        }

        i = 0;

        while(e < vertices - 1) {
            Edge nextEdge = pq.poll();
            int x = find(subsets, nextEdge.src);
            int y = find(subsets, nextEdge.dest);

            if(x != y) {
                result[e++] = nextEdge;
                union(subsets, x, y);
            }
        }

        for(i = 0; i < e; ++i) {
            System.out.println(result[i].src+" -- "+result[i].dest+" == "+ result[i].weight);
        }
    }
}
```
// generated by TicketToPR at 2025-11-17 04:53:51
