```java
// Declare the variables.
int number1 = 10;
int number2 = 5;

// Subtract number2 from number1 and store the result in subResult.
int subResult = number1 - number2;
```
// generated by TicketToPR at 2025-11-14 18:58:25
