```java
// This function subtracts two given numbers and returns the result.
public class Main {
    public static void main(String[] args) {
        int num1 = 10;
        int num2 = 5;
        
        // Call the subtractNumbers function and print the result
        System.out.println(subtractNumbers(num1, num2));
    }

    // Function to subtract two numbers
    public static int subtractNumbers(int num1, int num2) {
        // Subtract num2 from num1
        int result = num1 - num2;
        
        // Return the result
        return result;
    }
}
```
// generated by TicketToPR at 2025-11-14 18:56:29
