```java
// Java program to swap two numbers
public class SwapNumbers {
    
    public static void main(String[] args) {
        
        // Defining the two numbers to be swapped
        int a = 10;
        int b = 20;
 
        System.out.println("Before swap:");
        System.out.println("a = " + a);
        System.out.println("b = " + b);
        
        // Swap the numbers
        a = a + b; // Add both numbers and assign it to a
        b = a - b; // Subtract b from a and assign it to b
        a = a - b; // Subtract b from a and assign it to a
 
        System.out.println("After Swap:");
        System.out.println("a = " + a);
        System.out.println("b = " + b);
    }
}
```
In the above Java program, we begin by defining two integer variables, a and b, and assign them the numbers 10 and 20 respectively. We then display the original values of a and b.

Then, we swap the numbers without using a temporary variable. We add the values of a and b and store the result in a, then subtract the new value of b from a and assign the result to b, and finally subtract b from a again and assign the result to a. By doing this, a gets the original value of b and b gets the original value of a.

Finally, we display the new values of a and b, which shows that the numbers have been swapped.
// generated by TicketToPR at 2025-11-14 18:18:11
