```java
// Start of the class
public class SwapNumbers {

    public static void main(String[] args) {
        // Declare and initialize Two numbers
        int num1 = 10, num2 = 20;

        // Print numbers before swapping
        System.out.println("--Before Swap--");
        System.out.println("Number 1 = " + num1);
        System.out.println("Number 2 = " + num2);

        // Declare and use a third variable to swap the numbers
        int temp;
        temp = num1; // Temporarily store num1
        num1 = num2; // Assign the value of num2 to num1
        num2 = temp;  // Assign the temporarily stored num1 to num2

        // Print numbers after swapping
        System.out.println("--After Swap--");
        System.out.println("Number 1 = " + num1);
        System.out.println("Number 2 = " + num2);
    }
}
// End of class
```
// generated by TicketToPR at 2025-11-14 18:19:05
